name: Gerrit Dispatch
on:
- repository_dispatch

permissions:
  contents: write
  id-token: write
  actions: write

jobs:
  runtrybot:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    if: ${{ github.event.client_payload.type == 'gerrit' }}
    steps:
    - name: Write netrc file for Gerrit
      run: |-
        cat <<EOD > ~/.netrc
        machine gerrit.dev.edge.aviatrix.com
        login gha
        password ${{ secrets.GERRIT_GHA_PASSWORD }}
        EOD
        chmod 600 ~/.netrc
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Trigger CI
      run: |-
        git config user.name gha
        git config user.email noreply@aviatrix.com
        git fetch https://gha@gerrit.dev.edge.aviatrix.com/a/DolceTriade/monorepo ${{ github.event.client_payload.ref }}
        git checkout -b ci/${{ github.event.client_payload.changeID }}/${{ github.event.client_payload.commit }} FETCH_HEAD
        git push origin ci/${{ github.event.client_payload.changeID }}/${{ github.event.client_payload.commit }}